add_newline = true
format = "$hostname$directory$git_branch$git_status$nodejs$python$cmd_duration$line_break$character"

[hostname]
ssh_only = true
format = "[$hostname](bold red) "

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold yellow"

[cmd_duration]
min_time = 2000
format = "[$duration](yellow) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
